(ns css-sprite.core
  (:require [clojure.contrib.seq-utils :as seq-utils]
  					[clojure.contrib.duck-streams :as io])  
	(:import (java.io File 
										FilenameFilter)
					 (javax.imageio ImageIO)
					 (java.awt Color image.BufferedImage)))
  
(defprotocol Layout
  (sprite-dimensions [l images])
  (with-coordinates [l images]))

(deftype Vertical []
  :as this
  Layout
  (sprite-dimensions [i]
  	(let [images (with-coordinates this i)
  		    max-width (apply max (map #((:dimensions %1) 0) images))
  		    total-height (+ 
  		    						 	((:coordinates (last images)) 1)
  		    						 	((:dimensions (last images)) 1))]
  		[max-width total-height]))
  (with-coordinates [images]
  	(if (contains? (first images) :coordinates)
  		images
  		(let [heights (map #((:dimensions %1) 1) images)
	  	      y-positions (conj heights 0)]
				(for [[i image] (seq-utils/indexed images)]
					(merge image {:coordinates [0 (reduce + (take (inc i) y-positions))]}))))))

(def layouts {:vertical (Vertical)})

	  
(defn get-images 
	"Given a directory, return a map of all png images with a buffered image and dimensions"
	[dir]
	(let [d (io/file-str dir)]
		(when (.exists d)
			(map 
				(fn [file]
					(let [bi (ImageIO/read file)]
						{:buffered-image bi :path (.getPath file) :dimensions [(.getWidth bi) (.getHeight bi)]}))
				(filter 
					#(re-matches #".*\.png$" (.getName %1)) 
					(file-seq d))))))
					
(defn combine-images
	"Given the images and a layout type, create a sprite png at the output location"
	[images layout-type output]
	(let [layout						(layout-type layouts)
		    positioned-images (with-coordinates layout images)
		    output-dimensions (sprite-dimensions layout positioned-images) 
		    output-image      (BufferedImage. (output-dimensions 0) (output-dimensions 1) BufferedImage/TYPE_INT_ARGB)
				graphics          (.createGraphics output-image)]
		(doseq [image positioned-images]
			(.drawImage graphics (:buffered-image image) ((:coordinates image) 0) ((:coordinates image) 1) nil))
		(ImageIO/write output-image "png" (File. output))
		positioned-images))
		

(defn image->class-name
	[image]
	(:path image))

(defn write-css-selector
	[writer image]
	(let [class-name (str "." (image->class-name image))] 
		(.println writer (str class-name " {"))
		(.println writer (str "  background-position: " (:coordinates image)))
		(.println writer "}")))

(defn write-css
	[images layout-type output]
	(with-open [writer (io/writer (io/file-str output))]
			(.println writer (str "/* CSS Sprite File Generated by CSS-SPRITE.clj on " (java.util.Date.) " ...*/\n"))
			(count (for [image (with-coordinates (layout-type layouts) images)]
				(write-css-selector writer image)))))
								
			
			
			
			
			